name: Validate All Changes
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'main'
    paths:
      - '.github/build-object-client.yaml'
      - 'evo-object-client/**'

jobs:
  test-lint:
    name: "Test & Lint"
    uses: ./.github/workflows/python-tests-object-client.yaml
    secrets: inherit

  validate-docs:
    name: "Validate Documentation"
    runs-on: ubuntu-latest

    env:
      PIP_INDEX_URL: https://${{ secrets.AZUREARTIFACTS_RW }}@pkgs.dev.azure.com/bentleycs/Seequent/_packaging/Seequent-libraries/pypi/simple/

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate mkdocs
        uses: seequent/evo-client-library-automation/.github/actions/build-mkdocs@main

  bump-version:
    name: "Test Final Version Increment"
    uses: seequent/evo-client-library-automation/.github/workflows/python-bumpver.yaml@main
    with:
      tag-type: final
      extra-args: --dry
