name: Update Version & Deploy to Python Repository
on:
  push:
    branches:
      - main
    paths:
      - '.github/deploy-client-common.yaml'
      - 'evo-client-common/**'

  workflow_dispatch:
    inputs:
      tag-type:
        description: "Tag Type"
        required: false
        type: choice
        default: "dev"
        options:
          - "dev"
          - "alpha"
          - "beta"
          - "rc"

      version-type:
        description: "Release Type"
        required: false
        type: choice
        default: "none"
        options:
          - "none"
          - "patch"
          - "minor"
          - "major"

jobs:
  bump-version:
    name: "Update Version"
    uses: seequent/evo-client-library-automation/.github/workflows/python-bumpver.yaml@main
    with:
      tag-type: ${{ inputs.tag-type }}
      version-type: ${{ inputs.version-type }}
      artifact-name: ${{ vars.ARTIFACT_NAME }}
    permissions:
      contents: write

  test-lint:
    name: "Test & Lint"
    needs: bump-version
    uses: ./.github/workflows/python-tests-client-common.yaml

  publish-python-package:
    name: "Deploy to Python Repository"
    uses: seequent/evo-client-library-automation/.github/workflows/publish-python.yaml@main
    needs: test-lint
    if: ${{ needs.bump-version.outputs.artifact-available == 'true' }}
    with:
      artifact-name: ${{ vars.ARTIFACT_NAME }}
      repository-url: ${{ vars.PYTHON_REPOSITORY_URL }}
      repository-username: ${{ vars.PYTHON_REPOSITORY_USER }}
    secrets:
      repository-token: ${{ secrets.AZUREARTIFACTS_RW }}
