name: Publish Documentation
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - ".github/publish-docs-client-common.yaml"
      - "evo-client-common/**"
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish mkdocs
        uses: seequent/evo-client-library-automation/.github/actions/publish-mkdocs@main
