name: Test & Lint
on:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: ["3.10", "3.11", "3.12"]
        include:
          - os: ubuntu-latest
            python-version: "3.10"
            coverage-source: evo
            test-dir: tests
    runs-on: ${{ matrix.os }}

    env:
      PIP_INDEX_URL: https://${{ secrets.AZUREARTIFACTS_RW }}@pkgs.dev.azure.com/bentleycs/Seequent/_packaging/Seequent-libraries/pypi/simple/

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Tests
        id: tests
        uses: seequent/evo-client-library-automation/.github/actions/run-pytest@main
        with:
          python-version: ${{ matrix.python-version }}
          test-dir: tests
          coverage-source: ${{ matrix.coverage-source }}
          additional-dependencies: -e .[test]

  lint:
    runs-on: ubuntu-latest

    env:
      PIP_INDEX_URL: https://${{ secrets.AZUREARTIFACTS_RW }}@pkgs.dev.azure.com/bentleycs/Seequent/_packaging/Seequent-libraries/pypi/simple/

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Deps
        run: pip install --editable .[dev]

      - name: Linting (ruff)
        run: ruff check . --no-cache

      # Currently, ruff does not support linting and formatting in the same command.
      # https://docs.astral.sh/ruff/formatter/#sorting-imports
      - name: Formatting (ruff)
        run: ruff format --check . --no-cache
