name: "Install uv"
description: "Install python and uv"

inputs:
  PYTHON_VERSION:
    required: true
    description: "The Python version to run the tests on"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Set variables
      shell: bash
      run: |
        UV_VER=$(cat UV_VERSION)
        echo "UV_VERSION=$UV_VER" >> $GITHUB_ENV

    - name: Install uv ${{ env.UV_VERSION }} with Python ${{ inputs.python_version }}
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ inputs.python_version }}
        version: ${{ env.UV_VERSION }}
