site_name: Evo Object Client
use_directory_urls: false
watch:
- README.md
- src/evo
markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.superfences
- pymdownx.snippets:
    base_path:
    - .
    - ..
- toc:
    permalink: '#'
extra_css:
- stylesheet/extra.css
theme:
  name: material
  features:
  - navigation.sections
  - content.code.annotate
  - content.code.copy
  language: en
  custom_dir: docs/overrides
  logo: img/logo.svg
  favicon: img/favicon-16x16.png
  palette:
  - media: (prefers-color-scheme)
    scheme: default
    primary: black
    accent: deep purple
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: black
    accent: deep purple
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: black
    accent: deep purple
    toggle:
      icon: material/brightness-4
      name: Switch to system preference
plugins:
- search
- autorefs
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        paths:
        - src
        import:
        - https://docs.python.org/3/objects.inv
        options:
          docstring_style: sphinx
          heading_level: 2
          show_root_heading: true
          allow_inspection: true
          show_bases: true
          show_source: false
          show_category_heading: true
          inherited_members: true
          filters:
          - '!^__?'
          merge_init_into_class: true
          show_if_no_docstring: true
          show_signature: true
          separate_signature: true
          show_signature_annotations: true
- mkdocs-jupyter
- section-index
nav:
- Home: index.md
- Library:
  - Quickstart: quickstart.md
  - Object Service Client: object-service-client.md
  - Object Data Client: object-data-client.md
  - Data Types: data-types.md
- Notebooks:
  - Quickstart: examples/quickstart.ipynb
