[project]
name = "evo-objects"
version = "0.1.0"
requires-python = ">=3.10"
readme = { file = "README.md", content-type = "text/markdown" }
dependencies = [
    "evo-client-common>=0.1.0",
    "pydantic>=2,<3",
]

[build-system]
requires = ["setuptools >= 61.0.0"]
build-backend = "setuptools.build_meta"

[project.optional-dependencies]
aiohttp = ["evo-client-common[aiohttp]>=0.1.0"]
notebooks = ["evo-client-common[notebooks]>=0.1.0"]
utils = ["pyarrow", "pandas"]

[dependency-groups]
# Dev dependencies. The version is left unspecified so the latest is installed.
test = [
    "evo-objects[aiohttp,utils]",
    "pandas",
    "parameterized==0.9.0",
    "pytest",
]
dev = [
    "evo-objects[aiohttp,utils]",
    "bumpver",
    "coverage[toml]",
    "ruff",
    {include-group="test"},
]
notebooks = [
    "evo-objects[aiohttp,notebooks,utils]",
    "jupyter",
]

[tool.setuptools.packages.find]
where = ["src"]
namespaces = true

[tool.ruff]
src = ["src", "tests"]
line-length = 120

[tool.ruff.lint]
extend-select = ["I", "RUF022"]

[tool.bumpver]
current_version = "v0.1.0"
version_pattern = "vMAJOR.MINOR.PATCH[.PYTAGNUM]"
commit = "True"
tag = "True"
commit_message = "Bump version from {old_version} to {new_version}"

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'version = "{pep440_version}"',
    'current_version = "{version}"',
]
