name: "Publish"
description: "Builds and publishes a package"

inputs:
  PACKAGE:
    required: true
    description: "uv package to publish"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/install-uv

    - name: Build package
      shell: bash
      run: uv build --package ${{ inputs.package }}

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

    - name: Upload artifacts to GitHub Release
      uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda
      with:
        files: |
          dist
