name: "Publish"
description: "Builds and publishes a package"

inputs:
  TAG:
    required: true
    description: "GitHub release name/tag to upload artifacts to"
  PACKAGE:
    required: true
    description: "uv package to publish"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/install-uv

    - name: Build package
      shell: bash
      run: uv build --package ${{ inputs.package }}

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

    - name: Upload artifact to GitHub Release
      shell: bash
      run: gh release upload ${{ inputs.tag }} dist/*
