name: "Testing"
description: "Test a uv managed python project"

inputs:
  PACKAGE:
    required: true
    description: "uv package to run the tests in"

runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/install-uv

    - name: Pytest
      shell: bash
      run: |
        uv run --package ${{ inputs.package }} pytest ${{ inputs.package }}/tests/
