name: "Testing"
description: "Test a uv managed python project"

inputs:
  PACKAGE:
    required: true
    description: "uv package to run the tests in"
  PYTHON_VERSION:
    required: true
    description: "The Python version to run the tests on"

runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/install-uv
      with:
        PYTHON_VERSION: ${{ inputs.python_version }}

    - name: Pytest
      shell: bash
      run: |
        uv run --package ${{ inputs.package }} pytest packages/${{ inputs.package }}/tests/
