#  Copyright © 2025 Bentley Systems, Incorporated
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#      http://www.apache.org/licenses/LICENSE-2.0
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
"""
Workspaces API
=============

The Workspaces API enables users to organize, maintain, and store project data, but does not use or process the data. The workspace APIs allow you to manage:
- Workspaces
- User roles within workspaces
- Workspace thumbnails

There are three pre-defined roles within workspaces:

- Owner: can perform all actions in the workspace
- Editor: can perform all actions excluding deleting of a workspace
- Viewer: can view the workspace

These user roles can be assigned to users in a workspace. Once a role has been assigned it can be replaced or removed.
Users can also retrieve user roles, the role of a particular user, and their own role if applicable.
For more information on using the Workspaces API, see the [Workspaces API overview](https://developer.seequent.com/docs/guides/workspaces/), or the API references here.


This code is generated from the OpenAPI specification for Workspaces API.
API version: 1.0
"""

from evo.common.connector import APIConnector
from evo.common.data import EmptyResponse, RequestMethod
from evo.common.utils import get_header_metadata

from ..models import *  # noqa: F403

__all__ = ["FoldersApi"]


class FoldersApi:
    """API client for the Folders endpoint.

    NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    :param connector: Client for communicating with the API.
    """

    def __init__(self, connector: APIConnector):
        self.connector = connector

    async def create_folder(
        self,
        workspace_id: str,
        org_id: str,
        folder_create_request: FolderCreateRequest,  # noqa: F405
        api_preview: str | None = None,
        preview_api: str | None = None,
        additional_headers: dict[str, str] | None = None,
        request_timeout: float | tuple[int | float, int | float] | None = None,
    ) -> FolderResponse:  # noqa: F405
        """Create a folder

        Creates a new folder in the workspace. The folder needs to have a name and either a `parent_folder_id` or a `parent_folder_path`.

        :param workspace_id:
            Format: `uuid`
            Example: `'workspace_id_example'`
        :param org_id:
            Format: `uuid`
            Example: `'org_id_example'`
        :param folder_create_request:
            Example: `endpoints.FolderCreateRequest()`
        :param api_preview: (optional) Set to \"opt-in\" to be able to use this API.
            Example: `'api_preview_example'`
        :param preview_api: (optional) Set to \"opt-in\" to be able to use this API. This header is being deprecated. Please use the API-Preview header.
            Example: `'preview_api_example'`
        :param additional_headers: (optional) Additional headers to send with the request.
        :param request_timeout: (optional) Timeout setting for this request. If one number is provided, it will be the
            total request timeout. It can also be a pair (tuple) of (connection, read) timeouts.

        :return: Returns the result object.

        :raise evo.common.exceptions.BadRequestException: If the server responds with HTTP status 400.
        :raise evo.common.exceptions.UnauthorizedException: If the server responds with HTTP status 401.
        :raise evo.common.exceptions.ForbiddenException: If the server responds with HTTP status 403.
        :raise evo.common.exceptions.NotFoundException: If the server responds with HTTP status 404.
        :raise evo.common.exceptions.BaseTypedError: If the server responds with any other HTTP status between
            400 and 599, and the body of the response contains a descriptive `type` parameter.
        :raise evo.common.exceptions.EvoAPIException: If the server responds with any other HTTP status between 400
            and 599, and the body of the response does not contain a `type` parameter.
        :raise evo.common.exceptions.UnknownResponseError: For other HTTP status codes with no corresponding response
            type in `response_types_map`.
        """
        # Prepare the path parameters.
        _path_params = {
            "workspace_id": workspace_id,
            "org_id": org_id,
        }

        # Prepare the header parameters.
        _header_params = {
            "Content-Type": "application/json",
            "Accept": "application/json",
        } | get_header_metadata(__name__)
        if api_preview is not None:
            _header_params["API-Preview"] = api_preview
        if preview_api is not None:
            _header_params["Preview-API"] = preview_api
        if additional_headers is not None:
            _header_params.update(additional_headers)

        # Define the collection formats.
        _collection_formats = {}

        _response_types_map = {
            "200": FolderResponse,  # noqa: F405
            "201": FolderResponse,  # noqa: F405
        }

        return await self.connector.call_api(
            method=RequestMethod.POST,
            resource_path="/folder/instances/{org_id}/workspaces/{workspace_id}/folders",
            path_params=_path_params,
            header_params=_header_params,
            body=folder_create_request,
            collection_formats=_collection_formats,
            response_types_map=_response_types_map,
            request_timeout=request_timeout,
        )

    async def delete_folder(
        self,
        folder_id: str,
        workspace_id: str,
        org_id: str,
        api_preview: str | None = None,
        preview_api: str | None = None,
        additional_headers: dict[str, str] | None = None,
        request_timeout: float | tuple[int | float, int | float] | None = None,
    ) -> EmptyResponse:
        """Delete a folder

        Deletes the folder with the given ID. This is not a permanent delete, folder can be restored.

        :param folder_id:
            Format: `uuid`
            Example: `'folder_id_example'`
        :param workspace_id:
            Format: `uuid`
            Example: `'workspace_id_example'`
        :param org_id:
            Format: `uuid`
            Example: `'org_id_example'`
        :param api_preview: (optional) Set to \"opt-in\" to be able to use this API.
            Example: `'api_preview_example'`
        :param preview_api: (optional) Set to \"opt-in\" to be able to use this API. This header is being deprecated. Please use the API-Preview header.
            Example: `'preview_api_example'`
        :param additional_headers: (optional) Additional headers to send with the request.
        :param request_timeout: (optional) Timeout setting for this request. If one number is provided, it will be the
            total request timeout. It can also be a pair (tuple) of (connection, read) timeouts.

        :return: Returns the result object.

        :raise evo.common.exceptions.BadRequestException: If the server responds with HTTP status 400.
        :raise evo.common.exceptions.UnauthorizedException: If the server responds with HTTP status 401.
        :raise evo.common.exceptions.ForbiddenException: If the server responds with HTTP status 403.
        :raise evo.common.exceptions.NotFoundException: If the server responds with HTTP status 404.
        :raise evo.common.exceptions.BaseTypedError: If the server responds with any other HTTP status between
            400 and 599, and the body of the response contains a descriptive `type` parameter.
        :raise evo.common.exceptions.EvoAPIException: If the server responds with any other HTTP status between 400
            and 599, and the body of the response does not contain a `type` parameter.
        :raise evo.common.exceptions.UnknownResponseError: For other HTTP status codes with no corresponding response
            type in `response_types_map`.
        """
        # Prepare the path parameters.
        _path_params = {
            "folder_id": folder_id,
            "workspace_id": workspace_id,
            "org_id": org_id,
        }

        # Prepare the header parameters.
        _header_params = {} | get_header_metadata(__name__)
        if api_preview is not None:
            _header_params["API-Preview"] = api_preview
        if preview_api is not None:
            _header_params["Preview-API"] = preview_api
        if additional_headers is not None:
            _header_params.update(additional_headers)

        # Define the collection formats.
        _collection_formats = {}

        _response_types_map = {
            "204": EmptyResponse,
        }

        return await self.connector.call_api(
            method=RequestMethod.DELETE,
            resource_path="/folder/instances/{org_id}/workspaces/{workspace_id}/folders/{folder_id}",
            path_params=_path_params,
            header_params=_header_params,
            collection_formats=_collection_formats,
            response_types_map=_response_types_map,
            request_timeout=request_timeout,
        )

    async def get_folder_by_id(
        self,
        workspace_id: str,
        folder_id: str,
        org_id: str,
        deleted: bool | None = None,
        api_preview: str | None = None,
        preview_api: str | None = None,
        additional_headers: dict[str, str] | None = None,
        request_timeout: float | tuple[int | float, int | float] | None = None,
    ) -> FolderResponse:  # noqa: F405
        """Get folder by ID

        Returns a folder by its ID.

        :param workspace_id:
            Format: `uuid`
            Example: `'workspace_id_example'`
        :param folder_id:
            Format: `uuid`
            Example: `'folder_id_example'`
        :param org_id:
            Format: `uuid`
            Example: `'org_id_example'`
        :param deleted: (optional) Only show folders that have been deleted.
            Example: `False`
        :param api_preview: (optional) Set to \"opt-in\" to be able to use this API.
            Example: `'api_preview_example'`
        :param preview_api: (optional) Set to \"opt-in\" to be able to use this API. This header is being deprecated. Please use the API-Preview header.
            Example: `'preview_api_example'`
        :param additional_headers: (optional) Additional headers to send with the request.
        :param request_timeout: (optional) Timeout setting for this request. If one number is provided, it will be the
            total request timeout. It can also be a pair (tuple) of (connection, read) timeouts.

        :return: Returns the result object.

        :raise evo.common.exceptions.BadRequestException: If the server responds with HTTP status 400.
        :raise evo.common.exceptions.UnauthorizedException: If the server responds with HTTP status 401.
        :raise evo.common.exceptions.ForbiddenException: If the server responds with HTTP status 403.
        :raise evo.common.exceptions.NotFoundException: If the server responds with HTTP status 404.
        :raise evo.common.exceptions.BaseTypedError: If the server responds with any other HTTP status between
            400 and 599, and the body of the response contains a descriptive `type` parameter.
        :raise evo.common.exceptions.EvoAPIException: If the server responds with any other HTTP status between 400
            and 599, and the body of the response does not contain a `type` parameter.
        :raise evo.common.exceptions.UnknownResponseError: For other HTTP status codes with no corresponding response
            type in `response_types_map`.
        """
        # Prepare the path parameters.
        _path_params = {
            "workspace_id": workspace_id,
            "folder_id": folder_id,
            "org_id": org_id,
        }

        # Prepare the query parameters.
        _query_params = {}
        if deleted is not None:
            _query_params["deleted"] = deleted

        # Prepare the header parameters.
        _header_params = {
            "Accept": "application/json",
        } | get_header_metadata(__name__)
        if api_preview is not None:
            _header_params["API-Preview"] = api_preview
        if preview_api is not None:
            _header_params["Preview-API"] = preview_api
        if additional_headers is not None:
            _header_params.update(additional_headers)

        # Define the collection formats.
        _collection_formats = {}

        _response_types_map = {
            "200": FolderResponse,  # noqa: F405
        }

        return await self.connector.call_api(
            method=RequestMethod.GET,
            resource_path="/folder/instances/{org_id}/workspaces/{workspace_id}/folders/{folder_id}",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            collection_formats=_collection_formats,
            response_types_map=_response_types_map,
            request_timeout=request_timeout,
        )

    async def get_folder_by_path(
        self,
        workspace_id: str,
        org_id: str,
        deleted: bool | None = None,
        api_preview: str | None = None,
        preview_api: str | None = None,
        additional_headers: dict[str, str] | None = None,
        request_timeout: float | tuple[int | float, int | float] | None = None,
    ) -> FolderResponse:  # noqa: F405
        """Get folder by path.

        Get a folder at the provided path.

        :param workspace_id:
            Format: `uuid`
            Example: `'workspace_id_example'`
        :param org_id:
            Format: `uuid`
            Example: `'org_id_example'`
        :param deleted: (optional) Only show folders that have been deleted.
            Example: `False`
        :param api_preview: (optional) Set to \"opt-in\" to be able to use this API.
            Example: `'api_preview_example'`
        :param preview_api: (optional) Set to \"opt-in\" to be able to use this API. This header is being deprecated. Please use the API-Preview header.
            Example: `'preview_api_example'`
        :param additional_headers: (optional) Additional headers to send with the request.
        :param request_timeout: (optional) Timeout setting for this request. If one number is provided, it will be the
            total request timeout. It can also be a pair (tuple) of (connection, read) timeouts.

        :return: Returns the result object.

        :raise evo.common.exceptions.BadRequestException: If the server responds with HTTP status 400.
        :raise evo.common.exceptions.UnauthorizedException: If the server responds with HTTP status 401.
        :raise evo.common.exceptions.ForbiddenException: If the server responds with HTTP status 403.
        :raise evo.common.exceptions.NotFoundException: If the server responds with HTTP status 404.
        :raise evo.common.exceptions.BaseTypedError: If the server responds with any other HTTP status between
            400 and 599, and the body of the response contains a descriptive `type` parameter.
        :raise evo.common.exceptions.EvoAPIException: If the server responds with any other HTTP status between 400
            and 599, and the body of the response does not contain a `type` parameter.
        :raise evo.common.exceptions.UnknownResponseError: For other HTTP status codes with no corresponding response
            type in `response_types_map`.
        """
        # Prepare the path parameters.
        _path_params = {
            "workspace_id": workspace_id,
            "org_id": org_id,
        }

        # Prepare the query parameters.
        _query_params = {}
        if deleted is not None:
            _query_params["deleted"] = deleted

        # Prepare the header parameters.
        _header_params = {
            "Accept": "application/json",
        } | get_header_metadata(__name__)
        if api_preview is not None:
            _header_params["API-Preview"] = api_preview
        if preview_api is not None:
            _header_params["Preview-API"] = preview_api
        if additional_headers is not None:
            _header_params.update(additional_headers)

        # Define the collection formats.
        _collection_formats = {}

        _response_types_map = {
            "200": FolderResponse,  # noqa: F405
        }

        return await self.connector.call_api(
            method=RequestMethod.GET,
            resource_path="/folder/instances/{org_id}/workspaces/{workspace_id}/folders/path{folder_path}",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            collection_formats=_collection_formats,
            response_types_map=_response_types_map,
            request_timeout=request_timeout,
        )

    async def list_folders(
        self,
        workspace_id: str,
        org_id: str,
        path: str | None = None,
        folder_id: str | None = None,
        deleted: bool | None = None,
        depth: int | None = None,
        limit: int | None = None,
        offset: int | None = None,
        order_by: str | None = None,
        name: list[str] | None = None,
        created_by: list[str] | None = None,
        modified_by: list[str] | None = None,
        created_at: list[str] | None = None,
        modified_at: list[str] | None = None,
        api_preview: str | None = None,
        preview_api: str | None = None,
        additional_headers: dict[str, str] | None = None,
        request_timeout: float | tuple[int | float, int | float] | None = None,
    ) -> ListFoldersResponse:  # noqa: F405
        """List folders.

        Get a folder at the provided path/id with its child folders.

        :param workspace_id:
            Format: `uuid`
            Example: `'workspace_id_example'`
        :param org_id:
            Format: `uuid`
            Example: `'org_id_example'`
        :param path: (optional) Path to the folder to list children of.
            Format: `path`
            Example: `'path_example'`
        :param folder_id: (optional) ID of the folder to list children of.
            Format: `uuid`
            Example: `'folder_id_example'`
        :param deleted: (optional) Only show folders that have been deleted.
            Example: `False`
        :param depth: (optional) Max depth of child folders to return. Must be > 0 when provided.
            Example: `56`
        :param limit: (optional) Max number of results per page.
            Example: `100`
        :param offset: (optional) Number of results to skip before returning `limit` number of results.
            Example: `0`
        :param order_by: (optional) A comma separated list of fields to order by. The default sort order is ascending; prefix a field with `asc:` or `desc:` to specify its sort order. Defaults to `asc:depth,asc:path,desc:modified_at,asc:folder_id`. Supported fields: `name` (folder name), `path` (full folder path), `modified_at` (last modification time), `created_at` (creation time), `folder_id` (folder identifier), and `depth` (distance from the parent folder).
            Example: `'order_by_example'`
        :param name: (optional) Only show folders with a matching name. Supports the operators `eq` for an exact match (the default when no operator is given), `like`, and `ilike` for a pattern match. Also supports the `neq` operator for an exclusion. Patterns use `*` as a wildcard, which can be escaped with a backslash to match a literal `*`.
            Example: `['[\"reports\"]']`
        :param created_by: (optional) Filter by folders created by specific users
            Format: `uuid`
            Example: `['created_by_example']`
        :param modified_by: (optional) Filter by folders modified by specific users
            Format: `uuid`
            Example: `['modified_by_example']`
        :param created_at: (optional) Filter by folder creation time. Supports the operators `gte` (on or after) and `lte` (on or before), which must be specified explicitly. Values are ISO 8601 datetimes, e.g. `2026-08-01T00:00:00Z`. A value without a timezone is assumed to be UTC. Provide two values to filter by a range.
            Example: `['[\"gte:2026-08-01T00:00:00Z\"]']`
        :param modified_at: (optional) Filter by folder modification time. Supports the operators `gte` (on or after) and `lte` (on or before), which must be specified explicitly. Values are ISO 8601 datetimes, e.g. `2026-08-01T00:00:00Z`. A value without a timezone is assumed to be UTC. Provide two values to filter by a range.
            Example: `['[\"gte:2026-08-01T00:00:00Z\"]']`
        :param api_preview: (optional) Set to \"opt-in\" to be able to use this API.
            Example: `'api_preview_example'`
        :param preview_api: (optional) Set to \"opt-in\" to be able to use this API. This header is being deprecated. Please use the API-Preview header.
            Example: `'preview_api_example'`
        :param additional_headers: (optional) Additional headers to send with the request.
        :param request_timeout: (optional) Timeout setting for this request. If one number is provided, it will be the
            total request timeout. It can also be a pair (tuple) of (connection, read) timeouts.

        :return: Returns the result object.

        :raise evo.common.exceptions.BadRequestException: If the server responds with HTTP status 400.
        :raise evo.common.exceptions.UnauthorizedException: If the server responds with HTTP status 401.
        :raise evo.common.exceptions.ForbiddenException: If the server responds with HTTP status 403.
        :raise evo.common.exceptions.NotFoundException: If the server responds with HTTP status 404.
        :raise evo.common.exceptions.BaseTypedError: If the server responds with any other HTTP status between
            400 and 599, and the body of the response contains a descriptive `type` parameter.
        :raise evo.common.exceptions.EvoAPIException: If the server responds with any other HTTP status between 400
            and 599, and the body of the response does not contain a `type` parameter.
        :raise evo.common.exceptions.UnknownResponseError: For other HTTP status codes with no corresponding response
            type in `response_types_map`.
        """
        # Prepare the path parameters.
        _path_params = {
            "workspace_id": workspace_id,
            "org_id": org_id,
        }

        # Prepare the query parameters.
        _query_params = {}
        if path is not None:
            _query_params["path"] = path
        if folder_id is not None:
            _query_params["folder_id"] = folder_id
        if deleted is not None:
            _query_params["deleted"] = deleted
        if depth is not None:
            _query_params["depth"] = depth
        if limit is not None:
            _query_params["limit"] = limit
        if offset is not None:
            _query_params["offset"] = offset
        if order_by is not None:
            _query_params["order_by"] = order_by
        if name is not None:
            _query_params["name"] = name
        if created_by is not None:
            _query_params["created_by"] = created_by
        if modified_by is not None:
            _query_params["modified_by"] = modified_by
        if created_at is not None:
            _query_params["created_at"] = created_at
        if modified_at is not None:
            _query_params["modified_at"] = modified_at

        # Prepare the header parameters.
        _header_params = {
            "Accept": "application/json",
        } | get_header_metadata(__name__)
        if api_preview is not None:
            _header_params["API-Preview"] = api_preview
        if preview_api is not None:
            _header_params["Preview-API"] = preview_api
        if additional_headers is not None:
            _header_params.update(additional_headers)

        # Define the collection formats.
        _collection_formats = {
            "name": "multi",
            "created_by": "multi",
            "modified_by": "multi",
            "created_at": "multi",
            "modified_at": "multi",
        }

        _response_types_map = {
            "200": ListFoldersResponse,  # noqa: F405
        }

        return await self.connector.call_api(
            method=RequestMethod.GET,
            resource_path="/folder/instances/{org_id}/workspaces/{workspace_id}/folders",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            collection_formats=_collection_formats,
            response_types_map=_response_types_map,
            request_timeout=request_timeout,
        )

    async def restore_folder(
        self,
        folder_id: str,
        workspace_id: str,
        org_id: str,
        deleted: bool | None = None,
        api_preview: str | None = None,
        preview_api: str | None = None,
        additional_headers: dict[str, str] | None = None,
        request_timeout: float | tuple[int | float, int | float] | None = None,
    ) -> FolderResponse:  # noqa: F405
        """Restore a folder

        Restores a previously deleted folder.

        :param folder_id:
            Format: `uuid`
            Example: `'folder_id_example'`
        :param workspace_id:
            Format: `uuid`
            Example: `'workspace_id_example'`
        :param org_id:
            Format: `uuid`
            Example: `'org_id_example'`
        :param deleted: (optional) Only show folders that have been deleted.
            Example: `True`
        :param api_preview: (optional) Set to \"opt-in\" to be able to use this API.
            Example: `'api_preview_example'`
        :param preview_api: (optional) Set to \"opt-in\" to be able to use this API. This header is being deprecated. Please use the API-Preview header.
            Example: `'preview_api_example'`
        :param additional_headers: (optional) Additional headers to send with the request.
        :param request_timeout: (optional) Timeout setting for this request. If one number is provided, it will be the
            total request timeout. It can also be a pair (tuple) of (connection, read) timeouts.

        :return: Returns the result object.

        :raise evo.common.exceptions.BadRequestException: If the server responds with HTTP status 400.
        :raise evo.common.exceptions.UnauthorizedException: If the server responds with HTTP status 401.
        :raise evo.common.exceptions.ForbiddenException: If the server responds with HTTP status 403.
        :raise evo.common.exceptions.NotFoundException: If the server responds with HTTP status 404.
        :raise evo.common.exceptions.BaseTypedError: If the server responds with any other HTTP status between
            400 and 599, and the body of the response contains a descriptive `type` parameter.
        :raise evo.common.exceptions.EvoAPIException: If the server responds with any other HTTP status between 400
            and 599, and the body of the response does not contain a `type` parameter.
        :raise evo.common.exceptions.UnknownResponseError: For other HTTP status codes with no corresponding response
            type in `response_types_map`.
        """
        # Prepare the path parameters.
        _path_params = {
            "folder_id": folder_id,
            "workspace_id": workspace_id,
            "org_id": org_id,
        }

        # Prepare the query parameters.
        _query_params = {}
        if deleted is not None:
            _query_params["deleted"] = deleted

        # Prepare the header parameters.
        _header_params = {
            "Accept": "application/json",
        } | get_header_metadata(__name__)
        if api_preview is not None:
            _header_params["API-Preview"] = api_preview
        if preview_api is not None:
            _header_params["Preview-API"] = preview_api
        if additional_headers is not None:
            _header_params.update(additional_headers)

        # Define the collection formats.
        _collection_formats = {}

        _response_types_map = {
            "200": FolderResponse,  # noqa: F405
            "201": FolderResponse,  # noqa: F405
            "303": FolderResponse,  # noqa: F405
        }

        return await self.connector.call_api(
            method=RequestMethod.POST,
            resource_path="/folder/instances/{org_id}/workspaces/{workspace_id}/folders/{folder_id}",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            collection_formats=_collection_formats,
            response_types_map=_response_types_map,
            request_timeout=request_timeout,
        )

    async def summarize_folders(
        self,
        workspace_id: str,
        org_id: str,
        offset: int | None = None,
        limit: int | None = None,
        deleted: bool | None = None,
        api_preview: str | None = None,
        preview_api: str | None = None,
        additional_headers: dict[str, str] | None = None,
        request_timeout: float | tuple[int | float, int | float] | None = None,
    ) -> ListFoldersSummaryResponse:  # noqa: F405
        """Summarize folders.

        Get a summary of folders in this workspace.

        :param workspace_id:
            Format: `uuid`
            Example: `'workspace_id_example'`
        :param org_id:
            Format: `uuid`
            Example: `'org_id_example'`
        :param offset: (optional) Number of results to skip before returning `limit` number of results.
            Example: `0`
        :param limit: (optional) Max number of results per page.
            Example: `100`
        :param deleted: (optional) Only show folders that have been deleted.
            Example: `False`
        :param api_preview: (optional) Set to \"opt-in\" to be able to use this API.
            Example: `'api_preview_example'`
        :param preview_api: (optional) Set to \"opt-in\" to be able to use this API. This header is being deprecated. Please use the API-Preview header.
            Example: `'preview_api_example'`
        :param additional_headers: (optional) Additional headers to send with the request.
        :param request_timeout: (optional) Timeout setting for this request. If one number is provided, it will be the
            total request timeout. It can also be a pair (tuple) of (connection, read) timeouts.

        :return: Returns the result object.

        :raise evo.common.exceptions.BadRequestException: If the server responds with HTTP status 400.
        :raise evo.common.exceptions.UnauthorizedException: If the server responds with HTTP status 401.
        :raise evo.common.exceptions.ForbiddenException: If the server responds with HTTP status 403.
        :raise evo.common.exceptions.NotFoundException: If the server responds with HTTP status 404.
        :raise evo.common.exceptions.BaseTypedError: If the server responds with any other HTTP status between
            400 and 599, and the body of the response contains a descriptive `type` parameter.
        :raise evo.common.exceptions.EvoAPIException: If the server responds with any other HTTP status between 400
            and 599, and the body of the response does not contain a `type` parameter.
        :raise evo.common.exceptions.UnknownResponseError: For other HTTP status codes with no corresponding response
            type in `response_types_map`.
        """
        # Prepare the path parameters.
        _path_params = {
            "workspace_id": workspace_id,
            "org_id": org_id,
        }

        # Prepare the query parameters.
        _query_params = {}
        if offset is not None:
            _query_params["offset"] = offset
        if limit is not None:
            _query_params["limit"] = limit
        if deleted is not None:
            _query_params["deleted"] = deleted

        # Prepare the header parameters.
        _header_params = {
            "Accept": "application/json",
        } | get_header_metadata(__name__)
        if api_preview is not None:
            _header_params["API-Preview"] = api_preview
        if preview_api is not None:
            _header_params["Preview-API"] = preview_api
        if additional_headers is not None:
            _header_params.update(additional_headers)

        # Define the collection formats.
        _collection_formats = {}

        _response_types_map = {
            "200": ListFoldersSummaryResponse,  # noqa: F405
        }

        return await self.connector.call_api(
            method=RequestMethod.GET,
            resource_path="/folder/instances/{org_id}/workspaces/{workspace_id}/folders/summary",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            collection_formats=_collection_formats,
            response_types_map=_response_types_map,
            request_timeout=request_timeout,
        )

    async def update_folder(
        self,
        folder_id: str,
        workspace_id: str,
        org_id: str,
        folder_update_request: FolderUpdateRequest,  # noqa: F405
        api_preview: str | None = None,
        preview_api: str | None = None,
        additional_headers: dict[str, str] | None = None,
        request_timeout: float | tuple[int | float, int | float] | None = None,
    ) -> FolderResponse:  # noqa: F405
        """Update a folder

        Updates a folder's details.

        :param folder_id:
            Format: `uuid`
            Example: `'folder_id_example'`
        :param workspace_id:
            Format: `uuid`
            Example: `'workspace_id_example'`
        :param org_id:
            Format: `uuid`
            Example: `'org_id_example'`
        :param folder_update_request:
            Example: `endpoints.FolderUpdateRequest()`
        :param api_preview: (optional) Set to \"opt-in\" to be able to use this API.
            Example: `'api_preview_example'`
        :param preview_api: (optional) Set to \"opt-in\" to be able to use this API. This header is being deprecated. Please use the API-Preview header.
            Example: `'preview_api_example'`
        :param additional_headers: (optional) Additional headers to send with the request.
        :param request_timeout: (optional) Timeout setting for this request. If one number is provided, it will be the
            total request timeout. It can also be a pair (tuple) of (connection, read) timeouts.

        :return: Returns the result object.

        :raise evo.common.exceptions.BadRequestException: If the server responds with HTTP status 400.
        :raise evo.common.exceptions.UnauthorizedException: If the server responds with HTTP status 401.
        :raise evo.common.exceptions.ForbiddenException: If the server responds with HTTP status 403.
        :raise evo.common.exceptions.NotFoundException: If the server responds with HTTP status 404.
        :raise evo.common.exceptions.BaseTypedError: If the server responds with any other HTTP status between
            400 and 599, and the body of the response contains a descriptive `type` parameter.
        :raise evo.common.exceptions.EvoAPIException: If the server responds with any other HTTP status between 400
            and 599, and the body of the response does not contain a `type` parameter.
        :raise evo.common.exceptions.UnknownResponseError: For other HTTP status codes with no corresponding response
            type in `response_types_map`.
        """
        # Prepare the path parameters.
        _path_params = {
            "folder_id": folder_id,
            "workspace_id": workspace_id,
            "org_id": org_id,
        }

        # Prepare the header parameters.
        _header_params = {
            "Content-Type": "application/json",
            "Accept": "application/json",
        } | get_header_metadata(__name__)
        if api_preview is not None:
            _header_params["API-Preview"] = api_preview
        if preview_api is not None:
            _header_params["Preview-API"] = preview_api
        if additional_headers is not None:
            _header_params.update(additional_headers)

        # Define the collection formats.
        _collection_formats = {}

        _response_types_map = {
            "200": FolderResponse,  # noqa: F405
            "201": FolderResponse,  # noqa: F405
            "204": EmptyResponse,
        }

        return await self.connector.call_api(
            method=RequestMethod.PATCH,
            resource_path="/folder/instances/{org_id}/workspaces/{workspace_id}/folders/{folder_id}",
            path_params=_path_params,
            header_params=_header_params,
            body=folder_update_request,
            collection_formats=_collection_formats,
            response_types_map=_response_types_map,
            request_timeout=request_timeout,
        )
