name: Compile changelog

on:
  release:
    types: [released]

permissions:
  contents: write

jobs:
  compile-release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Add release notes to top of changelog
        run: |
          echo "# Changelog" >> new_entry
          echo "## ${{ github.event.release.tag_name }}" >> new_entry
          echo "${{ github.event.release.body }}" >> new_entry
          echo "" >> new_entry
          sed -i '/^# Changelog/d' CHANGELOG.md
          cat new_entry CHANGELOG.md > combined_entry && mv combined_entry CHANGELOG.md

      - name: Adjust heading levels and casing
        shell: bash
        run: |
          sed -i "s/^## What's Changed/### What's changed/g" CHANGELOG.md
          sed -i 's/^### Breaking Changes/#### Breaking changes/g' CHANGELOG.md
          sed -i 's/^### Other Changes/#### Other changes/g' CHANGELOG.md
          sed -i 's/^## New Contributors/### New contributors/g' CHANGELOG.md
          sed -i 's/\*\*Full Changelog\*\*:/\*\*Full changelog\*\*:/g' CHANGELOG.md

      - name: Remove all comments
        shell: bash
        run: |
          sed -i '/^<!--/d' CHANGELOG.md

      - name: Commit changes
        uses: iarekylew00t/verified-bot-commit@f6a8ea6511aea763df25b7c7e3788349f3d222c2
        with:
          message: "Add ${{ github.event.release.tag_name }} to changelog"
          files: |
            CHANGELOG.md

      - name: Push changes
        run: git push origin main
