name: Build and publish package

on:
  pull_request:
  # push:
  #   branches:
  #     - main

jobs:
  run-tests:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        package:
          - evo-client-common
          - evo-files
          - evo-objects
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/testing
        with:
          PYTHON_VERSION: ${{ matrix.python-version }}
          PACKAGE: ${{ matrix.package}}

  
  detect-changes:
    runs-on: ubuntu-latest
    name: Detect Packages with Changes
    permissions:
      contents: read
      pull-requests: read
    outputs:
      changes: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Define which paths constitute a change for each library. For now, 
      # a version bump needs a change in the pyproject.toml file, so use that.
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            evo-client-common:
              - 'packages/evo-client-common/pyproject.toml'
            evo-files:
              - 'packages/evo-files/pyproject.toml'
            evo-objects:
              - 'packages/evo-objects/pyproject.toml'

  build-package:
    name: Build packages
    needs: [run-tests, detect-changes]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ${{ needs.detect-changes.outputs.changes}}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-uv

      - name: Build
        shell: bash
        run: |
          uv build --package ${{ matrix.package }}
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./dist
          name: ${{ matrix.package }}

      # - name: Publish package to Artifactory
      #   if: github.repository == 'octo-org/octo-repo-prod'
      #   shell: bash
      #   run: |
      #     uv publish  --package ${{ matrix.package }} --index artifactory --username ${{ vars.EVO_ARTIFACTORY_USER }} --password ${{ secrets.EVO_ARTIFACTORY_TOKEN }}