name: Commit push trigger

on:
  push:

jobs:
  run-linting:
    name: Lint
    runs-on: ubuntu-latest
    uses: ./.github/actions/linting
  run-tests:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: [evo-client-common, evo-object-client]
    uses: ./.github/actions/testing
    with:
      PACKAGE: ${{ matrix.package}}
