name: Commit push Trigger

on:
  push:

jobs:
  run-linting:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/linting
  run-tests:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: [evo-client-common, evo-object-client]
      steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/testing
        with:
          PACKAGE: ${{ matrix.package}}
    