name: Commit push Trigger

on:
  push:

jobs:
  run-linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
        - uses: ./.github/actions/linting

        - run: echo "I did a thing"
    